### ISSUE TITLE
Values do not match the respective keys

### ISSUE THREAD

**Issue by massimoalbarello** [evrythng/epcis2.js#17]
The disposition in `cbv.js` contains two errors.

https://github.com/evrythng/epcis2.js/blob/5f35e70b26678b9d969a4763403fda20e2d9d1c7/src/cbv/cbv.js#L62
https://github.com/evrythng/epcis2.js/blob/5f35e70b26678b9d969a4763403fda20e2d9d1c7/src/cbv/cbv.js#L63

**Comment by clementh59** [comment]
Fixed in v2.0.0-beta.1
