### ISSUE TITLE
web-example can't work

### ISSUE THREAD

**Issue by gaeolus** [evrythng/epcis2.js#59]
open web-example/index.html,then chrome in check mode show 
Uncaught ReferenceError: module is not defined
    at epcis2.browser.js:11:632002
    at epcis2.browser.js:11:632006

module.exports = i     632002 line
}
)();                               632006 line

**Comment by clementh59** [comment]
Hi @gaeolus 

Good catch! Thanks a lot! 

It's fixed in the latest release: https://github.com/evrythng/epcis2.js/blob/master/example/web-example/index.html
